const ACTIONS = {
  JOIN: "join",
  JOINED: "joined",
  DISCONNECTED: "disconnected",
  LEAVE: "leave",
  CODE_CHANGED: "code-changed",
  SYNC_CODE: "sync-code",
  OUTPUT_CHANGED: "output-changed",
  LANGUAGE_CHANGED: "language-changed",
  ROOM_FULL: "room-full",
  JOIN_VIDEO: "join-video",
  ALL_USERS: "all-users",
  OFFER: "offer",
  GET_OFFER: "get-offer",
  ANSWER: "answer",
  GET_ANSWER: "get-answer",
  CANDIDATE: "candidate",
  GET_CANDIDATE: "get-candidate",
};
module.exports = ACTIONS;
